.TH XBACKLIGHT 1 1.0
.SH NAME
xbacklight \- adjust display and keyboard backlight using the /sys filesystem
.SH SYNOPSIS
.B xbacklight
[\-h|\-help] [\-ctrl \fICTRL\fP] [\-display \fIIGNORED\fP] [\-perceived]
[\-time \fIMILLISECS\fP] [\-steps \fISTEPS\fP | \-fps \fIFPS\fP] ...
.P
.B xbacklight
[flags] -list
.br
.B xbacklight
[flags] -get | \-getf | \-get-steps
.br
.B xbacklight
[flags] \-set \fIPERCENT\fP | \-inc \fIPERCENT\fP | \-dec \fIPERCENT\fP
.br
.B xbacklight
[flags] [=]\fIPERCENT\fP | +\fIPERCENT\fP | \-\fIPERCENT\fP
.SH DESCRIPTION
.I xbacklight
can query or set the brightness of display and keyboard backlight.
.I xbacklight
operates on the first device found in /sys/class/backlight, unless told
otherwise. Use \fI\-list\fP to see the full list of available devices that can
be used; then use the \fI-ctrl\fP flag to control them individually.
.SH QUERY OPERATIONS
.IP \-list
Print the list of controllable devices.
.IP \-get
Print out the backlight brightness as a percentage.
.IP \-getf
Same as \fI\-get\fP, but without rounding.
.IP \-get\-steps
Return the number of available brightness steps.
.SH SET OPERATIONS
The brightness can be set with either command flags or positional arguments.
When changing brightness level, both integer and fractional values (as reported
by \fI-get\fP and \fI-getf\fP respectively) are accepted.
.P
Regular set flags:
.IP "\-set \fIPERCENT\fP"
Sets the backlight brightness to the specified percentage level.
.IP "\-inc \fIPERCENT\fP"
Increases brightness by the specified amount.
.IP "\-dec \fIPERCENT\fP"
Decreases brightness by the specified amount.
.P
Set operations using positional arguments:
.P
.PD 0
.IP "\fBxbacklight \fIPERCENT"
.IP "\fBxbacklight \fI=PERCENT"
.PD
Set brightness (same as \fI\-set PERCENT\fP).
.IP "\fBxbacklight \fI+PERCENT"
Increase brightness (same as \fI\-inc PERCENT\fP).
.IP "\fBxbacklight \fI-PERCENT"
Decrease brightness (same as \fI\-dec PERCENT\fP).
.SH OPTIONS
.IP "-h, \-help"
Print out a summary of the usage and exit.
.IP "\-time \fIMILLISECONDS\fP"
Length of time to spend fading the backlight between old and new value.
Default is 200. Specifying either the number of fading steps
(with \fI\-steps\fP) or fading frame rate (with \fI-fps\fP) is required to
actually perform fading.
.IP "\-steps \fISTEPS\fP"
Number of fading steps.
.IP "\-fps \fIFPS\fP"
Target frame rate (frames/steps per second).
.IP "\-display \fIIGNORED\fP"
Ignored for backward compatibility.
.IP "\-ctrl \fICONTROLLER\fP"
Set the device name to operate on.
.IP "\-perceived"
Adjust the display according to the perceived brighness instead of operating on
the raw value directly.
.SH NOTES
.B xbacklight
doesn't lock the backlight device during fading. Running two concurrent fading
operations will result in backlight flickering.
.P
The backlight of most panels cannot be changed at a rate higher than 20-30hz.
Setting a high \fIFPS\fP value will not improve the transition smoothness
beyond a certain point.
.P
Most keyboard's backlights have a very coarse resolution, with usually only 4
brightness steps available. Use \fI-get-steps\fP to determine the available
resolution. Supplying small relative increments will not effectively change the
backlight illumination. Use large values (+30) or set absolute percentages
directly (=70).
.SH PORTABILITY
This version of \fBxbacklight\fP is part of "acpilight" and contains
several enhancements not available in the original version:
.P
The command-line flags \fI-list\fP, \fI-ctrl\fP, \fI-getf\fP, \fI-get-steps\fP,
\fI-perceived\fP and \fI-fps\fP do not exist in the original \fBxbacklight\fP.
.P
Fractional values are not allowed in the original \fBxbacklight\fP.
.P
The \fI=\fP (equals) is required by the original version when specifying
an absolute brightness value, but can be omitted in this version.
.SH AUTHORS
.B xbacklight
is part of \fIacpilight\fP (\fIhttps://gitlab.com/wavexx/acpilight\fP) and is
distributed under GPLv3+ \fBWITHOUT ANY WARRANTY\fP.
.br
Copyright(c) 2016-2018 by wave++ "Yuri D'Elia" <wavexx@thregr.org>.
